/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik.view;

import Connection.ConnectionManager;
import Controller.ExecuteDokter;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import klinik.view.MainView;
import Model.Dokter;

/**
 *
 * @author ASUS
 */
public class DokterView extends javax.swing.JFrame {
    String mencoba;
    /**
     * Creates new form HomeView
     */
    public DokterView(String input){
        initComponents();
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        buttonHome.setCursor(cursor);
        buttonPeriksa.setCursor(cursor);
        buttonKasir.setCursor(cursor);
        buttonObat.setCursor(cursor);
        buttonLogout.setCursor(cursor);
        
        mencoba = input;
         
    }

    private DokterView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        periksa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kasir = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        obat = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        denied = new javax.swing.JPanel();
        SidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnamapekerja = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonPeriksa = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonKasir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonObat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/clinic.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/unilever.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/wingsfood.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/topbrand.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/indonesia.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel23.setText("Healthy With");

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel24.setText("The first modern clinic for in Indonesia");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(7, 7, 7))
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel23))
                            .addComponent(jLabel19)))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel24))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel22)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(77, 77, 77)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel21))
                        .addGap(11, 11, 11)))
                .addGap(23, 23, 23))
        );

        bodyPanel.add(home, "card2");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 58)); // NOI18N
        jLabel6.setText("Diagnosis");

        javax.swing.GroupLayout periksaLayout = new javax.swing.GroupLayout(periksa);
        periksa.setLayout(periksaLayout);
        periksaLayout.setHorizontalGroup(
            periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periksaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        periksaLayout.setVerticalGroup(
            periksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periksaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(617, Short.MAX_VALUE))
        );

        bodyPanel.add(periksa, "card3");

        jLabel16.setText("kasir");

        javax.swing.GroupLayout kasirLayout = new javax.swing.GroupLayout(kasir);
        kasir.setLayout(kasirLayout);
        kasirLayout.setHorizontalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel16)
                .addContainerGap(784, Short.MAX_VALUE))
        );
        kasirLayout.setVerticalGroup(
            kasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel16)
                .addContainerGap(617, Short.MAX_VALUE))
        );

        bodyPanel.add(kasir, "card4");

        jLabel17.setText("obat");

        javax.swing.GroupLayout obatLayout = new javax.swing.GroupLayout(obat);
        obat.setLayout(obatLayout);
        obatLayout.setHorizontalGroup(
            obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel17)
                .addContainerGap(784, Short.MAX_VALUE))
        );
        obatLayout.setVerticalGroup(
            obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel17)
                .addContainerGap(617, Short.MAX_VALUE))
        );

        bodyPanel.add(obat, "card5");

        javax.swing.GroupLayout deniedLayout = new javax.swing.GroupLayout(denied);
        denied.setLayout(deniedLayout);
        deniedLayout.setHorizontalGroup(
            deniedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        deniedLayout.setVerticalGroup(
            deniedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        bodyPanel.add(denied, "card6");

        SidebarPanel.setBackground(new java.awt.Color(179, 47, 51));
        SidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/logohatikecil.png"))); // NOI18N
        SidebarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        txtnamapekerja.setBackground(new java.awt.Color(255, 255, 255));
        txtnamapekerja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnamapekerja.setForeground(new java.awt.Color(255, 255, 255));
        txtnamapekerja.setText("Muhamad Haikal");
        SidebarPanel.add(txtnamapekerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat datang, selamat bekerja");
        SidebarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        buttonLogout.setBackground(new java.awt.Color(179, 47, 51));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Keluar");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/logout.png"))); // NOI18N

        javax.swing.GroupLayout buttonLogoutLayout = new javax.swing.GroupLayout(buttonLogout);
        buttonLogout.setLayout(buttonLogoutLayout);
        buttonLogoutLayout.setHorizontalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        buttonLogoutLayout.setVerticalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(buttonLogoutLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        SidebarPanel.add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 230, 50));

        buttonHome.setBackground(new java.awt.Color(230, 56, 62));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/home.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Home");

        javax.swing.GroupLayout buttonHomeLayout = new javax.swing.GroupLayout(buttonHome);
        buttonHome.setLayout(buttonHomeLayout);
        buttonHomeLayout.setHorizontalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        buttonHomeLayout.setVerticalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 60));

        buttonPeriksa.setBackground(new java.awt.Color(179, 47, 51));
        buttonPeriksa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPeriksaMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/dokter.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Periksa");

        javax.swing.GroupLayout buttonPeriksaLayout = new javax.swing.GroupLayout(buttonPeriksa);
        buttonPeriksa.setLayout(buttonPeriksaLayout);
        buttonPeriksaLayout.setHorizontalGroup(
            buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPeriksaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        buttonPeriksaLayout.setVerticalGroup(
            buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPeriksaLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(buttonPeriksaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15))
        );

        SidebarPanel.add(buttonPeriksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 60));

        buttonKasir.setBackground(new java.awt.Color(179, 47, 51));
        buttonKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKasirMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kasir");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/kasir.png"))); // NOI18N

        javax.swing.GroupLayout buttonKasirLayout = new javax.swing.GroupLayout(buttonKasir);
        buttonKasir.setLayout(buttonKasirLayout);
        buttonKasirLayout.setHorizontalGroup(
            buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonKasirLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        buttonKasirLayout.setVerticalGroup(
            buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(buttonKasirLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        buttonObat.setBackground(new java.awt.Color(179, 47, 51));
        buttonObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonObatMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Obat");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/obat.png"))); // NOI18N

        javax.swing.GroupLayout buttonObatLayout = new javax.swing.GroupLayout(buttonObat);
        buttonObat.setLayout(buttonObatLayout);
        buttonObatLayout.setHorizontalGroup(
            buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonObatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        buttonObatLayout.setVerticalGroup(
            buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonObatLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        SidebarPanel.add(buttonObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/image/line.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        SidebarPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(home);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(230, 56, 62));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(179, 47, 51));
       
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonPeriksaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPeriksaMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(periksa);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(230, 56, 62));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(179, 47, 51));
    }//GEN-LAST:event_buttonPeriksaMouseClicked

    private void buttonKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKasirMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(kasir);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(230, 56, 62));
        buttonObat.setBackground(new Color(179, 47, 51));
    }//GEN-LAST:event_buttonKasirMouseClicked

    private void buttonObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonObatMouseClicked
        // hapus
        bodyPanel.removeAll();
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        //panggil
        bodyPanel.add(obat);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        buttonHome.setBackground(new Color(179, 47, 51));
        buttonPeriksa.setBackground(new Color(179, 47, 51));
        buttonKasir.setBackground(new Color(179, 47, 51));
        buttonObat.setBackground(new Color(230, 56, 62));
    }//GEN-LAST:event_buttonObatMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String sql = "Select * from dokter where username = '" + mencoba + "'";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.Logon();
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                txtnamapekerja.setText(rs.getString("nama")); 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }     
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterView().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel buttonHome;
    private javax.swing.JPanel buttonKasir;
    private javax.swing.JPanel buttonLogout;
    private javax.swing.JPanel buttonObat;
    private javax.swing.JPanel buttonPeriksa;
    private javax.swing.JPanel denied;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel kasir;
    private javax.swing.JPanel obat;
    private javax.swing.JPanel periksa;
    private javax.swing.JLabel txtnamapekerja;
    // End of variables declaration//GEN-END:variables
}
